### ISSUE TITLE
Hyak.Common.CloudException: InternalError: The server encountered an internal error

### ISSUE THREAD

**Issue by davenewza** [DarqueWarrior/custom-vso-agent-tasks#1]
There doesn't seem to exist a place to log issues but here. The STOP action is throwing the exception pasted below.

**Configuration:**

![image](https://cloud.githubusercontent.com/assets/6212830/24957034/96965c66-1f8a-11e7-9b07-1074d9def34e.png)

**Exception:**

> 2017-04-12T12:06:05.8208116Z ##[error]Hyak.Common.CloudException: InternalError: The server encountered an internal error. Please retry the request.
> 2017-04-12T12:06:05.8364332Z ##[error]   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> 2017-04-12T12:06:05.8364332Z ##[error]   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
> 2017-04-12T12:06:05.8364332Z ##[error]   at Microsoft.WindowsAzure.Management.WebSites.WebSiteOperationsExtensions.Update(IWebSiteOperations operations, String webSpaceName, String webSiteName, WebSiteUpdateParameters parameters)
> 2017-04-12T12:06:05.8364332Z ##[error]   at Microsoft.WindowsAzure.Commands.Utilities.Websites.WebsitesClient.ChangeWebsiteState(String name, String webspace, WebsiteState state) in D:\workspace\powershell-sign\src\ServiceManagement\Services\Commands.Utilities\Websites\WebsitesClient.cs:line 138
> 2017-04-12T12:06:05.8364332Z ##[error]   at Microsoft.WindowsAzure.Commands.Websites.StopAzureWebsiteCommand.ExecuteCmdlet() in D:\workspace\powershell-sign\src\ServiceManagement\Services\Commands\Websites\StopAzureWebSite.cs:line 31
> 2017-04-12T12:06:05.8364332Z ##[error]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord() in D:\workspace\powershell-sign\src\Common\Commands.Common\AzurePSCmdlet.cs:line 642
>

**Comment by davenewza** [comment]
So, this just came right eventually. Must have been an issue within VSTS.
